//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmenttbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departmenttbl()
        {
            this.Facultytbls = new HashSet<Facultytbl>();
        }
    
        public int DID { get; set; }
        public string DName_ { get; set; }
        public string DHOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facultytbl> Facultytbls { get; set; }
    }
}
