//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultytbl
    {
        public int FID { get; set; }
        public string FFname_ { get; set; }
        public string FLname_ { get; set; }
        public string FAddress { get; set; }
        public Nullable<int> DID { get; set; }
    
        public virtual Departmenttbl Departmenttbl { get; set; }
    }
}
